### ISSUE TITLE
Exception thrown after migrating to dotnet 9

### ISSUE THREAD

**Issue by CoolRamin** [dymaptic/GeoBlazor#370] opened 2024-12-13 21:35 UTC
The following exception is thrown in my Blazor server app after migrating to dotnet 9:

System.InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'dymaptic.GeoBlazor.Core.Components.Layers.GraphicsLayer'. There should only be one applicable constructor.

Below is my code snippet where the MapView component is injected:

`<MapView Class="map-view" OnClick="OnClick" Longitude="_longitude" Latitude="_latitude"
         Zoom="14" Style="height: 100%; width: 100%;" OnViewRendered="OnViewRendered">
    <Map>
        <Basemap>
            <OpenStreetMapLayer />
        </Basemap>
        <GraphicsLayer @ref="_graphicsLayer" />
    </Map>
</MapView>`

**Comment by AndersenBell** [comment] 2024-12-13 23:33
What version of GeoBlazor are you using?

We have seen this, it can usually be resolved by doing a full clean of the project. If that does not work, you can try to manually delete the bin/obj folders in your project and rebuild and see if the error still persists.

**Comment by CoolRamin** [comment] 2024-12-14 00:06
@AndersenBell 

I am using dymaptic.geoblazor.core 3.1.1
I did manually remove the bin and obj folder after migrating to dotnet 9. However, the issue still persists.

**Comment by TimPurdum** [comment] 2024-12-19 19:04
@CoolRamin just wanted to confirm, I can recreate this issue and am actively investigating it. We rely on multiple constructors to support both component markup and creating elements in code, so hopefully .NET hasn't removed that ability, but we shall see.

**Comment by TimPurdum** [comment] 2024-12-19 20:04
https://github.com/dotnet/aspnetcore/issues/40405 this was re-introduced after being reverted. Looks like we can fix it with an attribute, but will require adding that to all the empty constructors.

**Comment by TimPurdum** [comment] 2024-12-20 22:02
@CoolRamin version 3.1.2-beta-1 is up on Nuget if you need to stick with .NET 9. It fixes the exception, but your build times will still be really long until MS fixes https://github.com/dotnet/aspnetcore/issues/59014.

**Comment by CoolRamin** [comment] 2024-12-22 21:41
Thanks @TimPurdum for taking care of this issue so quickly. I appreciate it very much. I noticed longer than usual build time too. The app can display the map now, however I am getting below warnings in the console:

![Screenshot 2024-12-22 134001](https://github.com/user-attachments/assets/41b6ac1f-a76b-4b98-9f99-82240a88074b)

**Comment by TimPurdum** [comment] 2024-12-22 23:17
> Thanks @TimPurdum for taking care of this issue so quickly. I appreciate it very much. I noticed longer than usual build time too. The app can display the map now, however I am getting below warnings in the console:
> 
> ![Screenshot 2024-12-22 134001](https://github.com/user-attachments/assets/41b6ac1f-a76b-4b98-9f99-82240a88074b)
> 
> 

Interesting, the line in our code there is the main `view = new MapView()` call. The error sounds like something network related. I'll see if I can reproduce it, but I did check the console when I tested the beta package and didn't see that.

**Comment by CoolRamin** [comment] 2024-12-23 21:43
@TimPurdum 

I did a bit more investigation and figured out that the network error shown above was introduced after updating Microsoft.FluentUI.Components to version 4.11.0 in my application. Otherwise the update seems to address this issue properly. I am going to go ahead and closed this thread.

**Closed** 2024-12-23 21:43 UTC

**Comment by TimPurdum** [comment] 2024-12-23 21:44
@CoolRamin awesome, good to hear!
